name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.25

    steps:
      - uses: actions/checkout@v4

      - name: Download dependencies
        run: go mod tidy

      - name: Run vet
        run: go vet ./...

      - name: Run tests
        run: go test ./...
